# Site settings
title: The Malind Adventures
header-img: img/11130167_1661973657357855_3164546518501235825_o.jpg
email: malind.nikulski@gmail.com
copyright_name: Malind Kowalski
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mekowalski
learn_profile: mekowalski
email_username: malind.nikulski@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
